### ISSUE TITLE
Use without pip installation

### ISSUE THREAD

**Issue by drego85** [ninoseki/abuse_whois#21]
Hi @ninoseki and thanks for this beautiful tools.

Can I use this tools directly from the terminal (python3 xxxx.py https://...) without installing it from pip?

Thanks
Andrea

**Comment by ninoseki** [comment]
Excuse me, why?

**Comment by drego85** [comment]
I understand, it's a special/strange question  😅

But I would like to try to use this software in an environment where I don't have permission to install pip packages.

**Comment by ninoseki** [comment]
It is possible by unpacking the library and its dependencies manually and changing import paths. (Excuse me, I'm not willing to guide how to do that)

Another solution is setting up the REST API in somewhere and use it.

**Comment by drego85** [comment]
Ok, as I imagined. 

I preferred to have your feedback before making changes to the code (I was hoping I was wrong 😬).

Thanks a lot, I hope to help you support the project!
